routes:
  expose_internal: true
server:
  endpoint: 127.0.0.1:3000
storage:
  meilisearch:
    endpoint: http://localhost:7700
    api_key: 'aSampleMasterKey'
upload:
  s3:
    endpoint: http://localhost:9000
    bucket: batts
    access_key: minioadmin
    secret_key: minioadmin