services:
  backend:
    image: ghcr.io/dcnick3/batts:backend-03aae35767ee491e738e8a0cb0fd6e234dac685a
    environment:
      CONFIG_STORAGE__MEILISEARCH__ENDPOINT: "http://meilisearch:7700"
      CONFIG_STORAGE__MEILISEARCH__API_KEY: "aSampleMasterKey"
    ports:
      - 3000:3000
    depends_on:
      meilisearch:
        condition: service_healthy
  meilisearch:
    image: getmeili/meilisearch:v1.4
    environment:
      MEILI_ENV: "development"
    ports:
      - 7700:7700
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
