services:
  backend:
    image: ghcr.io/dcnick3/batts:backend-6bf6c870026c3ef97a9bc9211b72b4179d51535f
    environment:
      CONFIG_STORAGE__MEILISEARCH__ENDPOINT: "http://meilisearch:7700"
      CONFIG_STORAGE__MEILISEARCH__API_KEY: "aSampleMasterKey"
      CONFIG_UPLOAD__S3__ENDPOINT: "http://minio:9000"
    ports:
      - 3000:3000
    depends_on:
      meilisearch:
        condition: service_healthy
      minio:
        condition: service_healthy
  meilisearch:
    image: getmeili/meilisearch:v1.4
    environment:
      MEILI_ENV: "development"
    ports:
      - 7700:7700
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    command: minio server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ADDRESS: ':9000'
    ports:
      - 9000:9000
      - 9090:9090
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
