// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketDestination } from "./TicketDestination";

export interface CreateTicket { destination: TicketDestination, title: string, body: string, }