// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { UserId } from "./UserId";

export interface GroupView { id: GroupId, title: string, members: Array<UserId>, }