// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddGroupMember } from "./AddGroupMember";
import type { CreateGroup } from "./CreateGroup";

export type GroupCommand = { "type": "Create" } & CreateGroup | { "type": "AddMember" } & AddGroupMember;