// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadId } from "./UploadId";

export interface InitiatedUpload { id: UploadId, url: string, fields: Record<string, string>, expiration: string, }