// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchResultItem } from "./SearchResultItem";

export interface SearchResults<T> { top_hits: Array<SearchResultItem<T>>, }