// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TelegramLoginData { id: number, first_name: string, last_name: string, username: string | null, photo_url: string | null, auth_date: number, hash: string, }