// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TelegramProfile { id: bigint, first_name: string, last_name: string, username: string | null, photo_url: string | null, }