// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateTicket } from "./CreateTicket";
import type { SendTicketMessage } from "./SendTicketMessage";
import type { TicketStatus } from "./TicketStatus";

export type TicketCommand = { "type": "Create" } & CreateTicket | { "type": "SendTicketMessage" } & SendTicketMessage | { "type": "ChangeStatus" } & TicketStatus;