// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketId } from "./TicketId";
import type { UserId } from "./UserId";

export interface TicketView { id: TicketId, owner: UserId, title: string, messages: Array<string>, }