// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketTimelineItemContent } from "./TicketTimelineItemContent";

export interface TicketTimelineItem { date: string, content: TicketTimelineItemContent, }