// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UniversityProfile { email: string, commonname: string, family_name: string, given_name: string, }