// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalUserProfile } from "./ExternalUserProfile";

export type UpdateUser = { "type": "AddIdentity", profile: ExternalUserProfile, };