// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddGroupMember } from "./AddGroupMember";
import type { ChangeGroupTitle } from "./ChangeGroupTitle";
import type { RemoveGroupMember } from "./RemoveGroupMember";

export type UpdateGroup = { "type": "AddMember" } & AddGroupMember | { "type": "RemoveMember" } & RemoveGroupMember | { "type": "ChangeTitle" } & ChangeGroupTitle;