// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddGroupMember } from "./AddGroupMember";

export type UpdateGroup = { "type": "AddMember" } & AddGroupMember;