// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeAssignee } from "./ChangeAssignee";
import type { ChangeStatus } from "./ChangeStatus";
import type { SendTicketMessage } from "./SendTicketMessage";

export type UpdateTicket = { "type": "SendTicketMessage" } & SendTicketMessage | { "type": "ChangeStatus" } & ChangeStatus | { "type": "ChangeAssignee" } & ChangeAssignee;