// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UploadPolicy { allowed_file_extensions: Array<string>, allowed_content_types: Array<string>, max_size: bigint, }