// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalUserProfile } from "./ExternalUserProfile";

export type UserCommand = { "type": "Create", profile: ExternalUserProfile, } | { "type": "AddIdentity", profile: ExternalUserProfile, };