// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";
import type { UserIdentities } from "./UserIdentities";

export interface UserView { id: UserId, name: string, identities: UserIdentities, }