// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { GroupProfileView } from "./GroupProfileView";

export interface WithGroups<T> { groups: Record<GroupId, GroupProfileView>, payload: T, }