// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserId } from "./UserId";
import type { UserProfileView } from "./UserProfileView";

export interface WithUsers<T> { users: Record<UserId, UserProfileView>, payload: T, }