// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { GroupProfileView } from "./GroupProfileView";
import type { UserId } from "./UserId";
import type { UserProfileView } from "./UserProfileView";

export interface WithGroupsAndUsers<T> { groups: Record<GroupId, GroupProfileView>, users: Record<UserId, UserProfileView>, payload: T, }