### Hello World
GET {{url}}/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is text", function() {
        const type = response.contentType.mimeType;
        client.assert(type === "text/plain", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("Response body is correct", function() {
        client.assert(response.body === "Hello, World!", "Response body is not correct: " + response.body);
    });
%}

###
POST {{url}}/

### Create a new user
POST {{url}}/api/users/FDUeanyKADQEpyrydYn7XB
Content-Type: application/json

{
  "type": "Create",
  "profile": {
    "type": "Telegram",
    "id": 123456,
    "first_name": "Edward",
    "last_name": "Snowden"
  }
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200, but " + response.status);
    });

    client.test("Response content-type is application/json", function() {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    client.test("API envelope indicates success", function() {
        if (response.body.status !== "Success") {
            throw new Error("Response contains an error: " + response.body.payload.report);
        }
    });
%}

### Get user
GET {{url}}/api/users/FDUeanyKADQEpyrydYn7XB

### Get user by Telegram ID
GET {{url}}/api/user-identities/telegram-123456

### Log in
POST {{url}}/api/fake-login/FDUeanyKADQEpyrydYn7XB

### Create a ticket
POST {{url}}/api/tickets/F2VaZtXgAKgxJncCbMbX9V
Cookie: session=eyJhbGciOiJFZERTQSJ9.eyJleHAiOjE2OTY3MTA1NTcsImlhdCI6MTY5NjY5OTc1NywidXNlcl9pZCI6IkZEVWVhbnlLQURRRXB5cnlkWW43WEIiLCJuYW1lIjoiRWR3YXJkIFNub3dkZW4ifQ.wodYZRyBZMBwxeKqDrPJX2S6mKQwMBNH7Skb5GZeIBU53R3I08EOoTiytMXisqSV1bjPly4OqaCT2ZxkYGmCCw
Content-Type: application/json

{
  "type": "Create",
  "title": "Everything is broken",
  "body": "I can't log in to my account. Please help!"
}

### Get ticket
GET {{url}}/api/tickets/F2VaZtXgAKgxJncCbMbX9V