apiVersion: apps/v1
kind: Deployment
metadata:
  name: batts
  labels:
    app: batts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batts
  template:
    metadata:
      labels:
        app: batts
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        - name: batts-backend
          image: ghcr.io/dcnick3/batts:backend-7826dd4b147cc393e4b2ea7bbcdef9f2244b9359
          env:
            - name: CONFIG_SERVER__ENDPOINT
              value: "127.0.0.1:3001"
            - name: CONFIG_AUTH__TELEGRAM_SECRET
              valueFrom:
                secretKeyRef:
                  name: batts-secrets
                  key: telegram_secret
        - name: batts-frontend
          image: ghcr.io/dcnick3/batts:frontend-7826dd4b147cc393e4b2ea7bbcdef9f2244b9359
          env:
            - name: BACKEND_URL
              value: "http://127.0.0.1:3001"
          ports:
            - containerPort: 3000
