apiVersion: apps/v1
kind: Deployment
metadata:
  name: batts
  labels:
    app: batts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batts
  template:
    metadata:
      labels:
        app: batts
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        - name: batts-backend
          image: ghcr.io/dcnick3/batts:backend-6bf6c870026c3ef97a9bc9211b72b4179d51535f
          env:
            - name: CONFIG_SERVER__ENDPOINT
              value: "127.0.0.1:3001"
            - name: CONFIG_AUTH__TELEGRAM_SECRET
              valueFrom:
                secretKeyRef:
                  name: batts-secrets
                  key: telegram_secret
            - name: CONFIG_STORAGE__MEILISEARCH__ENDPOINT
              value: "http://batts-meilisearch.default.svc.cluster.local:7700"
            - name: CONFIG_STORAGE__MEILISEARCH__API_KEY
              valueFrom:
                secretKeyRef:
                  name: batts-meilisearch
                  key: MEILI_MASTER_KEY
            - name: CONFIG_UPLOAD__S3__ENDPOINT
              value: "https://minio-api.sakura.h.dcnick3.me"
            - name: CONFIG_UPLOAD__S3__BUCKET
              value: "batts"
            - name: CONFIG_UPLOAD__S3__ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: batts-secrets
                  key: s3_access_key
            - name: CONFIG_UPLOAD__S3__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: batts-secrets
                  key: s3_secret_key
        - name: batts-frontend
          image: ghcr.io/dcnick3/batts:frontend-6bf6c870026c3ef97a9bc9211b72b4179d51535f
          env:
            - name: BACKEND_URL
              value: "http://127.0.0.1:3001"
          ports:
            - containerPort: 3000
