apiVersion: apps/v1
kind: Deployment
metadata:
  name: batts
  labels:
    app: batts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batts
  template:
    metadata:
      labels:
        app: batts
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        # the backend goes first to be the one that gets the otel sdk injected
        # TODO: figure out the "multi-container instrumentation"
        # https://github.com/open-telemetry/opentelemetry-operator/blob/main/README.md#multi-container-pods-with-multiple-instrumentations
        - name: batts-backend
          image: ghcr.io/dcnick3/batts:backend-cee3fe2e94d591d1ee07ee31ca4d692c8a6a9b75
          env:
            - name: CONFIG_SERVER__ENDPOINT
              value: "127.0.0.1:3001"
        - name: batts-frontend
          image: ghcr.io/dcnick3/batts:frontend-a40abce6bc149173da7e97d68f4943e1aeb001fc
          env:
            - name: BACKEND_URL
              value: "http://127.0.0.1:3001"
          ports:
            - containerPort: 3000