apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batts-meilisearch
  namespace: argocd
spec:
  project: default
  source:
    chart: meilisearch
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    targetRevision: v0.2.8
    helm:
      values: |
        auth:
          existingMasterKeySecret: batts-meilisearch
        environment:
          MEILI_ENV: production
          MEILI_NO_ANALYTICS: true
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true